spring:
  application:
    name: wms

  datasource:
    url: jdbc:postgresql://localhost:5432/wms_db
    username: vaibhav
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
app:
  jwt:
    secret: "CHANGE_ME_this_must_be_at_least_256_bits_long_for_HS256_to_be_secure"
    access-token-expiration-minutes: 10
    refresh-token-expiration-days: 14
  cookie:
    secure: false   # local/dev default

server:
  port: 8080

